on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-monorepo-actions
      - uses: ./.github/actions/test-action